### ISSUE TITLE
Add code bundler

### ISSUE THREAD

**Issue by andyinabox** [jdalt/twin-cities-aid-distribution-locations#18]
browserify or something similar?

**Comment by jdalt** [comment]
This has been on the back of my mind. I like how easy it is to run this right now but the software engineer in me feels a need to make it easier to import libraries and bundle things.

I would rank this slightly lower in priority level since our near term ability get contributions and be as accessible as possible to develop for is really good. However we might be 100 or 200 lines of code from being quite yucky. This also sort of implies a build process which someone would probably need to automate through travis, jekyll, or github actions.

I'm guess what I'm saying is that if add a build process will also need to come with documentation in the readme and a deploy process.

**Comment by andyinabox** [comment]
Yes I agree, I was holding off for the same reason. @samanpwbb also suggested it so I figured worth capturing.

One thing to throw on this pile is switch over to something like Netlify free. There are a few advantages there, but one I think is worth mentioning is the ability to integrate into GH so that each PR gets a separate preview deploy. This allows people to test PRs without having to download and run themselves...

**Comment by andyinabox** [comment]
Actually I will capture the Netlify thing in a separate issue I think.

**Comment by andyinabox** [comment]
Added a comment to #24 re: Netlify

**Comment by andyinabox** [comment]
Here are some thoughts on implementation:

If we use [Snowpack](https://www.snowpack.dev/), it allows us to import via NPM but pre-builds the dependencies, rather than do something like webpack.

This allows us to keep deps in the repo so ppl don't necessarily need to have all the tooling set up to use (the NPM deps can be included as good old-fashioned `script` tags). This would also allow us to add a production build step that consolidates everything.

**Comment by jdalt** [comment]
Migrated to new repo
